Microsoft Windows [Version 10.0.22631.4602]
(c) Microsoft Corporation. All rights reserved.

(.venv) C:\Users\Dylan Burchfield\PycharmProjects\SentimentAnalysis>(.venv) C:\Users\Dylan Burchfield\PycharmProjects\SentimentAnalysis>